const Courses = [
   {
    id:"1",
    title:"Generalstudies 1",
    image:require("../../assets/gs1.jpeg"),
    description:"This cousres is design to cover static concept with thorough revisions of facts and its use in reacl life ",
    Course1:"Art and Culture",
    Course2:"History",
    Course3:"Society",
    Price:"3000",
   },
   {
    id:"2",
    title:"Generalstudies 2",
    image:require("../../assets/gs2.jpeg"),
    description:"This cousres is design to cover dynamic concept with a basic understanding of constitution and administration",
    Course1:"Polity",
    Course2:"Governance",
    Course3:"International Relations",
    Price:"5000",
   },
   {
    id:"3",
    title:"Generalstudies 3",
    image:require("../../assets/gs3.jpeg"),
    description:"This cousres is design to cover the concept and topics which relatable to future life wealth of a country and its security along with the sustanilbilty",
    Course1:"Economy",
    Course2:"Environment",
    Course3:"Internal Security",
    Price:"10,000",
   },
   {
    id:"4",
    title:"Generalstudies 4",
    image:require("../../assets/gs4.jpeg"),
    description:" A course of moral and Value as Civil servants",
    Course1:"case Study",
    Course2:" Ethical Topical",
    Course3:" Admininstrative Knowledge",
    Price:"2000",
   },
   {
    id:"5",
    title:"Essay writing",
    image:require("../../assets/essay.png"),
    description:" A good marks is behind good strategy and hard Work for this we have taught you <b>How to Write Proper essay</b>",
    Course1:"Essay in story Formate",
    Course2:"Philosophical essay",
    Course3:" General studies Essay",
    Price:"6000",
   },
   {
    id:"6",
    title:"Prelims",
    image:require("../../assets/prelims.jpeg"),
    description:"take tset of mcq for selection",
    Course1:"general studies",
    Course2:" CSAT",
    Course3:"Current Affairs",
    Price:"5000",
   },
   {
    id:"7",
    title:"Answer writing",
    image:require("../../assets/answer.png"),
    description:" Pratice Regular Answers for good marks",
    Course1:"Topic wise Answers",
    Course2:" Check and Feedback",
    Course3:"Diagram and quality enhacement",
    Price:"6008",
   },   
]
 export default Courses;